---
management_interface: FastEthernet1/1
ospf_router_id: 3.3.3.3

ospf_networks:
  - network: 10.0.34.0
    wildcard: 0.0.0.3
    area: 0

  - network: 192.168.60.0
    wildcard: 0.0.0.255
    area: 0

  - network: 192.168.70.0
    wildcard: 0.0.0.255
    area: 0
