---
- name: Ensure SSH version 2 is enabled
  cisco.ios.ios_config:
    lines:
      - ip ssh version 2
    save_when: modified

- name: Ensure VTY uses local login and SSH only
  cisco.ios.ios_config:
    parents:
      - line vty 0 4
    lines:
      - login local
      - transport input ssh
    match: line
    save_when: modified
