---
- name: Configure VLAN subinterfaces
  hosts: routers
  gather_facts: no

  tasks:

    - name: R1 VLAN 10
      cisco.ios.ios_config:
        parents: interface FastEthernet0/0.10
        lines:
          - description VLAN10_ADMIN
          - encapsulation dot1Q 10
          - ip address 192.168.10.1 255.255.255.0
      when: inventory_hostname == "R1"

    - name: R1 VLAN 20
      cisco.ios.ios_config:
        parents: interface FastEthernet0/0.20
        lines:
          - description VLAN20_STAFF
          - encapsulation dot1Q 20
          - ip address 192.168.20.1 255.255.255.0
      when: inventory_hostname == "R1"

    - name: R1 VLAN 30
      cisco.ios.ios_config:
        parents: interface FastEthernet0/0.30
        lines:
          - description VLAN30_IT
          - encapsulation dot1Q 30
          - ip address 192.168.30.1 255.255.255.0
      when: inventory_hostname == "R1"

    - name: R2 VLAN 40
      cisco.ios.ios_config:
        parents: interface FastEthernet0/0.40
        lines:
          - description VLAN40_BRANCH_STAFF
          - encapsulation dot1Q 40
          - ip address 192.168.40.1 255.255.255.0
      when: inventory_hostname == "R2"

    - name: R2 VLAN 50
      cisco.ios.ios_config:
        parents: interface FastEthernet0/0.50
        lines:
          - description VLAN50_BRANCH_ADMIN
          - encapsulation dot1Q 50
          - ip address 192.168.50.1 255.255.255.0
      when: inventory_hostname == "R2"

    - name: R3 VLAN 60
      cisco.ios.ios_config:
        parents: interface FastEthernet0/0.60
        lines:
          - description VLAN60_SERVERS
          - encapsulation dot1Q 60
          - ip address 192.168.60.1 255.255.255.0
      when: inventory_hostname == "R3"

    - name: R3 VLAN 70
      cisco.ios.ios_config:
        parents: interface FastEthernet0/0.70
        lines:
          - description VLAN70_DATABASE
          - encapsulation dot1Q 70
          - ip address 192.168.70.1 255.255.255.0
      when: inventory_hostname == "R3"
